import type { ParsedPRD, Phase, ProgressState } from '../types.js';

export function generateMainPRD(prd: ParsedPRD, outputDir: string): string {
  return `# ${prd.projectInfo.name} - Task Breakdown

> Generated by vibe-assistant from your PRD

## Overview

${prd.overview.summary}

### Goals
${prd.overview.goals.map((g) => `- ${g}`).join('\n')}

---

## Implementation Roadmap

${prd.phases.map((phase) => `
### Phase ${phase.number}: ${phase.name}
${phase.description}

**Entry Criteria:**
${phase.entryCriteria.map((c) => `- ${c}`).join('\n')}

**Exit Criteria:**
${phase.exitCriteria.map((c) => `- ${c}`).join('\n')}

**Tasks:** See \`${outputDir}/phases/phase-${phase.number}.md\` for detailed task breakdown.
`).join('\n')}

---

## Context Instructions for AI Agents

> **IMPORTANT:** This section contains instructions for AI coding agents working on this project.

### Before Starting Any Work
1. Read this entire document to understand the full scope
2. Check \`docs/progress/state.json\` for current progress
3. Read the relevant phase file in \`${outputDir}/phases/\`

### During Implementation
1. Work through phases sequentially
2. Complete all tasks in a phase before moving to the next
3. After each task, run \`/checkpoint\` to save progress

### Maintaining Context
1. Re-read relevant sections of this document when starting new tasks
2. Reference \`docs/progress/\` summaries for context on completed work
3. Keep task descriptions in sync with actual implementation

### File Structure
\`\`\`
${outputDir}/
├── PRD.md (this file)
└── phases/
    ├── phase-1.md
    └── ...

docs/progress/
├── state.json
└── phase-*-summary.md
\`\`\`
`;
}

export function generatePhaseFile(phase: Phase, prd: ParsedPRD): string {
  return `# Phase ${phase.number}: ${phase.name}

> Part of [${prd.projectInfo.name} PRD](../PRD.md)

## Overview
${phase.description}

## Entry Criteria
${phase.entryCriteria.map((c) => `- [ ] ${c}`).join('\n')}

## Exit Criteria
${phase.exitCriteria.map((c) => `- [ ] ${c}`).join('\n')}

---

## Tasks

${phase.tasks.map((task, index) => `
### ${index + 1}. ${task.title}
**ID:** \`${task.id}\`
**Status:** ${task.status}
**Parallelizable:** ${task.parallelizable ? 'Yes' : 'No'}
**Dependencies:** ${task.dependencies.length > 0 ? task.dependencies.map((d) => `\`${d}\``).join(', ') : 'None'}

${task.description}
`).join('\n---\n')}

---

## Completion Checklist

When all tasks are complete:
1. [ ] All exit criteria met
2. [ ] Tests passing for this phase
3. [ ] Run \`/checkpoint\` to update progress
4. [ ] Proceed to Phase ${phase.number + 1} (if applicable)
`;
}

export function generateInitialState(prd: ParsedPRD): ProgressState {
  const tasks: ProgressState['tasks'] = {};

  for (const phase of prd.phases) {
    for (const task of phase.tasks) {
      tasks[task.id] = { status: 'pending' };
    }
  }

  return {
    currentPhase: 1,
    tasks,
    checkpoints: [],
    lastUpdated: new Date().toISOString(),
  };
}
